package com.opentasker.core.huawei.pgnss

import java.io.File
import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder

/**
 * The orchestration, end to end, with the network replaced by committed files.
 *
 * Every fixture here is REAL data with nothing altered but the satellites and epochs dropped from
 * it: `e2e-code.sp3` is CODE's five-day prediction of 2026-08-30 cut to six satellites at 900 s,
 * the two `e2e-wuhan-*.sp3` are Wuhan's near-real-time multi-GNSS product cut to three BeiDou
 * satellites at 1800 s, the almanacs are the files the reference implementation was last run on,
 * and `captured/` holds the first blocks of Huawei's own set. Nothing in this directory was
 * generated by this code.
 *
 * ## What this grades and what it does not
 * The arithmetic is graded elsewhere, against the Python: [RecordsTest] compares the encoders and
 * the assembler byte for byte, [PgnssFitTest] compares the fits by the reference's own error
 * measure, [PropagatorTest] compares the integrator against `pgnss_orbit.py`'s numbers, and
 * [ExtraFileTest] compares `HW_PGNSS_EXTRA` against the bytes the reference produced. None of that
 * is repeated here.
 *
 * What is graded here is the WIRING, and it is graded the way `scripts/pgnss-verify.py` grades it:
 * by asking whether every byte position Huawei's own file uses carries something in ours, and
 * whether every position they leave alone stays alone in ours. That check knows nothing about what
 * the fields mean, which is the point — it is what would have caught byte 77, the one byte nobody
 * wrote and therefore nobody read, which cost a 3-4 minute fix where Huawei's file gave 21 s.
 *
 * And the refusals. A build that quietly substitutes a stale file for a missing input is the exact
 * failure this whole feature exists to stop, so three of the tests below do nothing but take an
 * input away and check that the build says so and writes NOTHING.
 */
class PredictedSetTest {

    @get:Rule
    val temp = TemporaryFolder()

    /**
     * 2026-08-30 11:59:42 UTC in full GPS seconds, a multiple of 7200.
     *
     * Pinned, not taken from the clock: the fixtures are a real day's orbit products and the window
     * has to fall inside them. The 72 hours it opens run to 2026-09-02 10:00 GPS, which is inside
     * the five-day prediction and past the end of every BeiDou product that exists — so the BeiDou
     * path really does splice one day from the product and integrate the other two.
     */
    private val nowGps = 1_472_126_400L

    // ── the whole set ───────────────────────────────────────────────────────────────────────────

    @Test
    fun theWholeSetIsBuiltFromCommittedSourcesAndPassesTheFieldCoverageCheck() {
        val out = temp.newFolder("store")
        val work = temp.newFolder("work")
        stageCaptured(File(out, PredictedSet.CAPTURED_DIR))
        val reports = ArrayList<PgnssProgress>()

        val result = runBlocking {
            PredictedSet.build(
                workDir = work,
                outDir = out,
                nowGpsSeconds = nowGps,
                sources = fixtureSources(),
                progress = { reports.add(it) },
            )
        }

        // 1. All six, at the sizes the layout fixes. These are the sizes Huawei's own files have.
        assertEquals(PredictedSet.NAMES.toSet(), result.files.keys.toSet())
        assertEquals(93_312, File(out, PredictedSet.NAME_GPS).length().toInt())
        assertEquals(99_648, File(out, PredictedSet.NAME_GALILEO).length().toInt())
        assertEquals(361_584, File(out, PredictedSet.NAME_GLONASS).length().toInt())
        assertEquals(209_808, File(out, PredictedSet.NAME_BDS).length().toInt())
        assertEquals(6_248, File(out, PredictedSet.NAME_EXTRA).length().toInt())
        for (name in listOf(
            PredictedSet.NAME_GPS, PredictedSet.NAME_GALILEO,
            PredictedSet.NAME_GLONASS, PredictedSet.NAME_BDS, PredictedSet.NAME_EXTRA,
        )) {
            assertEquals(
                "$name is not the size its layout fixes",
                PredictedSet.expectedSize(name), File(out, name).length().toInt(),
            )
        }
        // QZSS is carried, not made: its invariant is that it is the capture, byte for byte.
        assertArrayEquals(
            "QZSS must be the captured file unchanged",
            fixtureBytes("captured/HW_PGNSS_QZS"),
            File(out, PredictedSet.NAME_QZS).readBytes(),
        )

        // 2. Nothing is left in the store but the six and the capture it was seeded with.
        assertEquals(
            (PredictedSet.NAMES + PredictedSet.CAPTURED_DIR).sorted(),
            out.list()!!.sorted(),
        )

        // 3. The stamps: 36 blocks 7200 s apart, GLONASS an hour early, BeiDou 14 s late.
        val gps = stamps(File(out, PredictedSet.NAME_GPS).readBytes())
        assertEquals(nowGps, gps.first())
        assertEquals(setOf(7200L), gps.zipWithNext { a, b -> b - a }.toSet())
        assertEquals(
            gps.map { it - 3600L },
            stamps(File(out, PredictedSet.NAME_GLONASS).readBytes()),
        )
        assertEquals(
            gps.map { it + Records.BDS_STAMP_OFFSET },
            stamps(File(out, PredictedSet.NAME_BDS).readBytes()),
        )

        // 4. `scripts/pgnss-verify.py`, in Kotlin, against the captured excerpts.
        val divergences = ArrayList<String>()
        for ((name, reclen) in listOf(
            PredictedSet.NAME_GPS to Records.GPS_RECLEN,
            PredictedSet.NAME_GALILEO to Records.GALILEO_RECLEN,
            PredictedSet.NAME_BDS to Records.BDS_RECLEN,
        )) {
            divergences += fieldCoverage(
                name,
                records(File(out, name).readBytes(), reclen),
                records(fixtureBytes("captured/$name"), reclen),
                reclen,
            )
        }
        assertEquals(
            "every field Huawei's capture uses must carry something in ours, and every field they " +
                "leave alone must stay alone in ours:\n" + divergences.joinToString("\n"),
            emptyList<String>(), divergences,
        )

        // 5. Every block carries satellites. A block of zeros is not a prediction.
        for ((name, reclen, capacity) in listOf(
            Triple(PredictedSet.NAME_GPS, Records.GPS_RECLEN, Records.GPS_CAPACITY),
            Triple(PredictedSet.NAME_GALILEO, Records.GALILEO_RECLEN, Records.GALILEO_CAPACITY),
            Triple(PredictedSet.NAME_BDS, Records.BDS_RECLEN, Records.BDS_CAPACITY),
        )) {
            val counts = blockCounts(File(out, name).readBytes(), reclen)
            assertEquals("$name has ${counts.size} blocks", 36, counts.size)
            assertTrue("$name has an empty block: $counts", counts.all { it in 1..capacity })
        }

        // 6. The progress contract: real counts, a bar that only goes forwards, both steps used.
        assertTrue("nothing was reported", reports.isNotEmpty())
        var last = -1.0
        for (p in reports) {
            assertTrue("the bar went backwards: $last -> ${p.fraction}", p.fraction >= last)
            last = p.fraction
            assertTrue("count ${p.done}/${p.total} is not a real count", p.done <= p.total || p.total == 0)
        }
        assertEquals(1.0, reports.last().fraction, 1e-9)
        assertEquals(
            setOf(PgnssStep.DOWNLOAD, PgnssStep.BUILD),
            reports.map { it.step }.toSet(),
        )
        val fits = reports.filter { it.phase.startsWith("Fitting") }
        assertTrue("the fit reported no units at all", fits.isNotEmpty() && fits.last().total > 0)

        println("  " + result.summary)
        for (note in result.notes) println("    $note")
    }

    // ── the refusals ────────────────────────────────────────────────────────────────────────────

    /**
     * The failure that shipped an expired BeiDou file while reporting success.
     *
     * A build with no usable Earth-orientation file cannot integrate BeiDou. The one thing it must
     * NOT do is quietly serve the copy that is already in the store — so the store is given a stale
     * file first, and the test insists it is still there, untouched, afterwards.
     */
    @Test
    fun aMissingEarthOrientationFileRefusesTheBuildAndLeavesTheStoreAlone() {
        val out = temp.newFolder("store")
        stageCaptured(File(out, PredictedSet.CAPTURED_DIR))
        val stale = File(out, PredictedSet.NAME_BDS)
        stale.writeBytes(fixtureBytes("captured/HW_PGNSS_BDS"))
        val before = stale.readBytes()

        val error = refuse(out, temp.newFolder("work")) {
            it.copy(codeErp = emptyErp())
        }

        assertTrue(error.message!!, "Earth-orientation" in error.message!!)
        assertArrayEquals("the stale file was replaced or rewritten", before, stale.readBytes())
        assertEquals(
            "a refused build must write nothing at all",
            listOf(PredictedSet.CAPTURED_DIR, PredictedSet.NAME_BDS).sorted(),
            out.list()!!.sorted(),
        )
    }

    /** Without Huawei's capture there is no BeiDou group delay and no QZSS. That is a refusal. */
    @Test
    fun aMissingCaptureRefusesTheBuild() {
        val out = temp.newFolder("store")
        val error = refuse(out, temp.newFolder("work")) { it }
        assertTrue(error.message!!, "captured" in error.message!!)
        assertTrue("nothing may be written", out.list()!!.none { it.startsWith("HW_PGNSS") })
    }

    /** An orbit product that stops inside the window cannot make one, and must not pretend to. */
    @Test
    fun anOrbitProductTooShortForTheWindowIsRefused() {
        val out = temp.newFolder("store")
        stageCaptured(File(out, PredictedSet.CAPTURED_DIR))
        // The same sources, a window three days later than the product describes.
        val late = runCatching {
            runBlocking {
                PredictedSet.build(
                    workDir = temp.newFolder("work-late"),
                    outDir = out,
                    nowGpsSeconds = nowGps + 3 * 86400L,
                    sources = fixtureSources(),
                )
            }
        }.exceptionOrNull()
        assertTrue("expected a refusal, got $late", late is PgnssBuildException)
        assertTrue(late!!.message!!, "window" in late.message!!)
        assertTrue("nothing may be written", out.list()!!.none { it.startsWith("HW_PGNSS") })
    }

    /** The BeiDou product carrying no BeiDou is not a reason to reach for the captured copy. */
    @Test
    fun anOrbitProductWithNoBeiDouIsRefusedRatherThanSubstituted() {
        val out = temp.newFolder("store")
        stageCaptured(File(out, PredictedSet.CAPTURED_DIR))
        val error = refuse(out, temp.newFolder("work")) {
            // The CODE prediction stands in for Wuhan's: real SP3, no BeiDou in it.
            it.copy(wuhanOrbits = listOf(it.codeSp3))
        }
        assertTrue(error.message!!, "no BeiDou" in error.message!!)
        assertTrue("nothing may be written", out.list()!!.none { it.startsWith("HW_PGNSS") })
    }

    // ── helpers ─────────────────────────────────────────────────────────────────────────────────

    private fun refuse(
        out: File,
        work: File,
        mangle: (PgnssSources) -> PgnssSources,
    ): PgnssBuildException {
        val thrown = runCatching {
            runBlocking {
                PredictedSet.build(
                    workDir = work,
                    outDir = out,
                    nowGpsSeconds = nowGps,
                    sources = PgnssSourceSupplier { dir, _ -> mangle(sources(dir)) },
                )
            }
        }.exceptionOrNull()
        assertTrue("expected a refusal, got $thrown", thrown is PgnssBuildException)
        return thrown as PgnssBuildException
    }

    private fun fixtureSources() = PgnssSourceSupplier { dir, _ -> sources(dir) }

    /** The committed fixtures, copied into [dir] exactly as a download would have left them. */
    private fun sources(dir: File): PgnssSources {
        dir.mkdirs()
        fun put(fixture: String, name: String): File =
            File(dir, name).also { it.writeBytes(fixtureBytes(fixture)) }
        return PgnssSources(
            codeSp3 = put("e2e-code.sp3", "COD0OPSPRD_05D.SP3"),
            codeErp = put("code-predicted.erp", "COD0OPSPRD_ERP.ERP"),
            wuhanOrbits = listOf(
                put("e2e-wuhan-1.sp3", "WUM0MGXNRT_1_02D_05M_ORB.SP3"),
                put("e2e-wuhan-2.sp3", "WUM0MGXNRT_2_02D_05M_ORB.SP3"),
            ),
            egm96 = put("egm96-deg12.gfc", "EGM96.gfc"),
            yuma = put("e2e-yuma.alm", "current_yuma.alm"),
            galileoXml = put("e2e-galileo.xml", "galileo.xml"),
            glonassAgl = put("e2e-glonass.agl", "MCCT.agl"),
            brdcNav = listOf(put("e2e-brdc.rnx", "BRDC00WRD_R_MN.rnx")),
        )
    }

    private fun emptyErp(): File =
        temp.newFile("empty.erp").also { it.writeText("VERSION 2\nnot an ERP\n") }

    private fun stageCaptured(dir: File) {
        dir.mkdirs()
        for (name in listOf("HW_PGNSS_GPS", "HW_PGNSS_GALILEO", "HW_PGNSS_BDS", "HW_PGNSS_QZS")) {
            File(dir, name).writeBytes(fixtureBytes("captured/$name"))
        }
    }

    private fun fixtureBytes(name: String): ByteArray = PgnssFixtures.bytes(name)

    // ── the verifier ────────────────────────────────────────────────────────────────────────────

    /**
     * Byte positions whose use depends on WHEN the window falls, not on whether a field is written.
     *
     * BeiDou stores toc and toe as 32-bit counts of 8 s of the BeiDou week, which runs to 75600 and
     * needs SEVENTEEN bits: the third byte of each is 1 for a window late in the week and 0 for one
     * early in it. Huawei's two captured vintages fail this check against EACH OTHER on exactly
     * these two offsets and nothing else, which is as clear a statement as the format is going to
     * make that they are not a field. The GPS week (bytes 2-3) is the same kind of thing: a counter,
     * whose meaning is written down in `Records.encodeGps`.
     */
    private val epochDependent = setOf(
        PredictedSet.NAME_BDS to 10, PredictedSet.NAME_BDS to 30,
        PredictedSet.NAME_GPS to 2, PredictedSet.NAME_GPS to 3,
    )

    private fun fieldCoverage(
        name: String,
        ours: List<ByteArray>,
        capture: List<ByteArray>,
        reclen: Int,
    ): List<String> {
        assertTrue("$name: nothing to compare", ours.isNotEmpty() && capture.isNotEmpty())
        val out = ArrayList<String>()
        for (offset in 0 until reclen) {
            if (name to offset in epochDependent) continue
            val captureZero = capture.all { it[offset].toInt() == 0 }
            val oursZero = ours.all { it[offset].toInt() == 0 }
            if (captureZero && !oursZero) {
                out.add(
                    "$name off $offset: the capture is always 0, ours sets ${values(ours, offset)} " +
                        "— we write where they do not",
                )
            } else if (oursZero && !captureZero) {
                out.add(
                    "$name off $offset: the capture sets ${values(capture, offset)}, ours is always " +
                        "0 — we leave a field they fill",
                )
            } else if (!captureZero) {
                val theirs = capture.mapTo(HashSet()) { it[offset] }
                val mine = ours.mapTo(HashSet()) { it[offset] }
                if (theirs.size == 1 && mine.size == 1 && theirs != mine) {
                    out.add(
                        "$name off $offset: the capture is constantly ${theirs.first()}, ours is " +
                            "constantly ${mine.first()} — a flag disagrees",
                    )
                }
            }
        }
        return out
    }

    private fun values(records: List<ByteArray>, offset: Int): String =
        records.mapTo(sortedSetOf()) { it[offset].toInt() and 0xFF }.take(8).joinToString(",")

    private fun records(bytes: ByteArray, reclen: Int): List<ByteArray> {
        val out = ArrayList<ByteArray>()
        for (i in 0 until Records.BLOCKS) {
            val offset = u32(bytes, 12 * i + 4)
            if (offset < 1008 || offset + 4 > bytes.size) continue
            val count = u32(bytes, offset)
            for (k in 0 until count) {
                val from = offset + 4 + k * reclen
                if (from + reclen > bytes.size) break
                out.add(bytes.copyOfRange(from, from + reclen))
            }
        }
        return out
    }

    private fun blockCounts(bytes: ByteArray, reclen: Int): List<Int> =
        (0 until Records.BLOCKS).mapNotNull { i ->
            val offset = u32(bytes, 12 * i + 4)
            if (offset < 1008 || offset + 4 > bytes.size) null else u32(bytes, offset)
        }

    private fun stamps(bytes: ByteArray): List<Long> =
        (0 until Records.BLOCKS).map { u32(bytes, 12 * it).toLong() and 0xFFFFFFFFL }

    private fun u32(b: ByteArray, off: Int): Int =
        (b[off].toInt() and 0xFF) or ((b[off + 1].toInt() and 0xFF) shl 8) or
            ((b[off + 2].toInt() and 0xFF) shl 16) or ((b[off + 3].toInt() and 0xFF) shl 24)
}
