package com.opentasker.docs

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import java.nio.file.Files
import java.nio.file.Path
import javax.xml.parsers.DocumentBuilderFactory

class DependencyVerificationContractTest {
    private val repoRoot: Path = listOf(Path.of("."), Path.of(".."))
        .first { Files.exists(it.resolve("README.md")) && Files.exists(it.resolve("gradle/verification-metadata.xml")) }

    @Test
    fun metadataRequiresReviewedUpstreamProvenanceAndSignatures() {
        val factory = DocumentBuilderFactory.newInstance().apply { isNamespaceAware = true }
        val document = factory.newDocumentBuilder()
            .parse(repoRoot.resolve("gradle/verification-metadata.xml").toFile())
        val namespace = "https://schema.gradle.org/dependency-verification"
        val checksums = document.getElementsByTagNameNS(namespace, "sha256")
        val origins = (0 until checksums.length).map { index ->
            checksums.item(index).attributes.getNamedItem("origin")?.nodeValue
        }

        val verifySignatures = document.getElementsByTagNameNS(namespace, "verify-signatures").item(0)?.textContent?.trim()
        assertEquals("Signature verification must be enabled", "true", verifySignatures)
        assertTrue("An explicit trusted-key set is required", document.getElementsByTagNameNS(namespace, "trusted-key").length > 0)
        assertEquals("Blanket trusted-artifacts entries are forbidden", 0, document.getElementsByTagNameNS(namespace, "trusted-artifacts").length)
        assertTrue("Every checksum must record provenance", origins.all { it?.startsWith("OpenTasker: ") == true })
        assertFalse("Gradle-generated origins must not ship", origins.any { it?.startsWith("Generated by Gradle") == true })
    }

    @Test
    fun verifierChecksPublishedSidecarsAndExplicitFallbacks() {
        val script = repoRoot.resolve("tools/verify-dependency-verification.ps1").toFile().readText()
        assertTrue("Verifier must support upstream SHA-256 sidecars", ".sha256" in script)
        assertTrue("Verifier must support upstream detached signatures", ".asc" in script)
        assertTrue("Verifier must hash direct upstream artifacts when no sidecar exists", "direct artifact SHA-256" in script)
        assertTrue("Verifier must reject generated origins", "Generated by Gradle" in script)
    }
}
