package com.opentasker.ui

import org.junit.Assert.assertFalse
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.nio.file.Files
import java.nio.file.Path
import javax.xml.parsers.DocumentBuilderFactory
import kotlin.io.path.readText

class LocalizationSourceTest {
    private val moduleRoot: Path = listOf(Path.of("."), Path.of("app"))
        .first { Files.isDirectory(it.resolve("src/main")) }
    private val sourceRoot: Path = moduleRoot.resolve("src/main/java")
    private val resRoot: Path = moduleRoot.resolve("src/main/res")





    @Test
    fun debugBuildGeneratesAndroidPseudoLocales() {
        val buildFile = moduleRoot.resolve("build.gradle.kts").readText()
        assertTrue(
            "Debug builds must enable Android en-XA/ar-XB pseudo locales",
            Regex("""getByName\(\"debug\"\)\s*\{[^}]*isPseudoLocalesEnabled\s*=\s*true""", RegexOption.DOT_MATCHES_ALL)
                .containsMatchIn(buildFile),
        )
    }

    @Test
    fun localeDirectoriesMeetTheReleaseCompletionThreshold() {
        val buildFile = moduleRoot.resolve("build.gradle.kts").readText()
        assertTrue(
            "Per-app language selection must be generated by AGP",
            "generateLocaleConfig = true" in buildFile,
        )
        assertTrue(
            "The default locale must be explicit for generated locale config",
            "unqualifiedResLocale=en-US" in resRoot.resolve("resources.properties").readText(),
        )
        val threshold = Regex("""LOCALE_COMPLETION_THRESHOLD\s*=\s*(0\.\d+)""")
            .find(buildFile)
            ?.groupValues
            ?.get(1)
            ?.toDouble()
            ?: error("Locale completion threshold is not declared in the build script")
        val defaultValueFiles = Files.list(resRoot.resolve("values")).use { paths ->
            paths.filter { Files.isRegularFile(it) && it.fileName.toString().endsWith(".xml") }.toList()
        }
        assertTrue("Default value resources are missing", defaultValueFiles.isNotEmpty())

        val localeDirectories = Files.list(resRoot).use { paths ->
            paths
                .filter { Files.isDirectory(it) && it.fileName.toString().startsWith("values-") }
                .toList()
        }
        val defaultStrings = defaultValueFiles.flatMap { stringResourceValues(it).entries }.associate { it.toPair() }
        val failures = localeDirectories.mapNotNull { directory ->
            val localeFiles = Files.list(directory).use { paths ->
                paths.filter { Files.isRegularFile(it) && it.fileName.toString().endsWith(".xml") }.toList()
            }
            if (localeFiles.isEmpty()) return@mapNotNull null
            val invalidFiles = localeFiles.mapNotNull { file ->
                runCatching {
                    val root = newDocumentBuilderFactory().newDocumentBuilder().parse(file.toFile()).documentElement.nodeName
                    if (root == "resources") null else "${resRoot.relativize(file)} root=$root"
                }.getOrElse { error -> "${resRoot.relativize(file)} ${error.message}" }
            }
            if (invalidFiles.isNotEmpty()) return@mapNotNull "Invalid XML: $invalidFiles"
            val localeStrings = localeFiles
                .flatMap { stringResourceValues(it).entries }
                .associate { it.toPair() }
            val unknownNames = localeStrings.keys - defaultStrings.keys
            if (unknownNames.isNotEmpty()) {
                return@mapNotNull "${directory.fileName} defines unknown strings: $unknownNames"
            }
            val translated = defaultStrings.count { (name, english) ->
                localeStrings[name] != null && localeStrings[name] != english
            }
            val completion = translated.toDouble() / defaultStrings.size
            if (completion < threshold) {
                "${directory.fileName} is below ${(threshold * 100).toInt()}%: $translated/${defaultStrings.size}"
            } else {
                null
            }
        }

        assertTrue("Locale completeness failures: $failures", failures.isEmpty())
    }

    private fun defaultStringResourceNames(): Set<String> =
        Files.list(resRoot.resolve("values")).use { paths ->
            paths
                .filter { Files.isRegularFile(it) && it.fileName.toString().endsWith(".xml") }
                .flatMap { file ->
                    val document = newDocumentBuilderFactory().newDocumentBuilder().parse(file.toFile())
                    val strings = document.getElementsByTagName("string")
                    (0 until strings.length).map { index ->
                        strings.item(index).attributes.getNamedItem("name").nodeValue
                    }.stream()
                }
                .toList()
                .toSet()
        }

    private fun newDocumentBuilderFactory(): DocumentBuilderFactory =
        DocumentBuilderFactory.newInstance().apply {
            setFeature("http://apache.org/xml/features/disallow-doctype-decl", true)
            setFeature("http://xml.org/sax/features/external-general-entities", false)
            setFeature("http://xml.org/sax/features/external-parameter-entities", false)
            isXIncludeAware = false
            isExpandEntityReferences = false
        }

    private fun stringResourceValues(file: Path): Map<String, String> {
        val document = newDocumentBuilderFactory().newDocumentBuilder().parse(file.toFile())
        val strings = document.getElementsByTagName("string")
        return (0 until strings.length).associate { index ->
            val item = strings.item(index)
            item.attributes.getNamedItem("name").nodeValue to item.textContent.trim()
        }
    }
// RETIRED: upstream's rule that every visible string resolves through a string resource. This fork is
// single-user and single-language by design — Japanese copy is authored inline, deliberately, across the
// action catalog, Setup and the overlays. Routing it through resources would add indirection for a
// translation that will never exist.
}
