package com.opentasker.core.share

import android.content.Context
import android.content.SharedPreferences
import androidx.core.content.edit
import com.opentasker.core.icons.TaskIconStore
import com.opentasker.core.share.relay.RelayPackaging
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/** Where a target's generated relay APK stands relative to its current label/icon. */
enum class RelayState {
    /** Configured but no relay installed yet. */
    DRAFT,

    /** A relay is installed and matches the current label/icon. */
    GENERATED,

    /** Label or icon changed since the installed relay was built — needs regenerating. */
    STALE,
}

/**
 * One share target: an app that gets its own relay APK (own package = own system-share-sheet tile).
 * [targetPackage] is the app the relay forwards to (and unfreezes); [relayPackage] is the generated
 * relay's own package. [label]/[iconPath] are the editable tile identity.
 */
@Serializable
data class ShareRelayEntry(
    val targetPackage: String,
    val label: String,
    val iconPath: String? = null,
    val relayPackage: String,
    val state: RelayState = RelayState.DRAFT,
    /** The signing-cert fingerprint the installed relay was built with (detects key rotation). */
    val signedFingerprint: String? = null,
)

/**
 * Process-wide, SharedPreferences-backed list of share-relay targets. Device-local: the app selection
 * never leaves the phone. Deliberately does NOT touch the launcher/share-sheet itself — the relay APKs
 * (generated by `core/share/relay/`) are what appear in the sheet; this store is the bookkeeping the
 * "Share apps" screen and [ShareForwardActivity] read. Mirrors the FreezeBubbleStore pattern; [init]
 * runs once in Application.onCreate.
 */
object ShareRelayStore {
    private const val PREFS_NAME = "shiroikuma_share_relays"
    private const val K_RELAYS = "relays_json"
    private const val K_COPY_STREAMS = "copy_streams"

    const val MAX_TARGETS = 8

    private val json = Json { ignoreUnknownKeys = true; encodeDefaults = true }
    private lateinit var prefs: SharedPreferences
    private val _relays = MutableStateFlow<List<ShareRelayEntry>>(emptyList())
    val relays: StateFlow<List<ShareRelayEntry>> = _relays.asStateFlow()

    /**
     * When on, forwarded content:// streams are copied into our FileProvider and re-shared from there
     * (fallback for receivers that reject a re-delegated grant). Read by [ShareForwardActivity].
     */
    var copyStreams: Boolean
        get() = ::prefs.isInitialized && prefs.getBoolean(K_COPY_STREAMS, false)
        set(value) { if (::prefs.isInitialized) prefs.edit { putBoolean(K_COPY_STREAMS, value) } }

    fun init(context: Context) {
        prefs = context.applicationContext.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        _relays.value = load()
    }

    /** Resolve by the TARGET package — used by [ShareForwardActivity] when a relay forwards in. */
    fun find(targetPackage: String): ShareRelayEntry? = _relays.value.firstOrNull { it.targetPackage == targetPackage }

    /** Add a new target draft (or return the existing entry). Icon defaults to the app's launcher icon. */
    fun addDraft(targetPackage: String, label: String, iconPath: String?) {
        if (!::prefs.isInitialized) return
        if (find(targetPackage) != null || _relays.value.size >= MAX_TARGETS) return
        commit(_relays.value + ShareRelayEntry(
            targetPackage = targetPackage,
            label = label,
            iconPath = iconPath,
            relayPackage = RelayPackaging.relayPackage(targetPackage),
        ))
    }

    /** Edit the label; marks the relay STALE (needs regenerating) if it was already generated. */
    fun setLabel(targetPackage: String, label: String) = mutate(targetPackage) {
        it.copy(label = label, state = if (it.state == RelayState.GENERATED) RelayState.STALE else it.state)
    }

    /** Edit the icon; deletes the old snapshot and marks STALE if generated. */
    fun setIcon(targetPackage: String, iconPath: String?) = mutate(targetPackage) {
        if (it.iconPath != iconPath) TaskIconStore.delete(it.iconPath)
        it.copy(iconPath = iconPath, state = if (it.state == RelayState.GENERATED) RelayState.STALE else it.state)
    }

    /** Record a successful install of the relay with the signing fingerprint it was built with. */
    fun markGenerated(targetPackage: String, fingerprint: String) = mutate(targetPackage) {
        it.copy(state = RelayState.GENERATED, signedFingerprint = fingerprint)
    }

    /** Flag an entry as needing regeneration (e.g. signing key rotated). */
    fun markStale(targetPackage: String) = mutate(targetPackage) { it.copy(state = RelayState.STALE) }

    fun remove(targetPackage: String) {
        if (!::prefs.isInitialized) return
        find(targetPackage)?.let { TaskIconStore.delete(it.iconPath) }
        commit(_relays.value.filterNot { it.targetPackage == targetPackage })
    }

    private fun mutate(targetPackage: String, f: (ShareRelayEntry) -> ShareRelayEntry) {
        if (!::prefs.isInitialized) return
        commit(_relays.value.map { if (it.targetPackage == targetPackage) f(it) else it })
    }

    private fun commit(list: List<ShareRelayEntry>) {
        _relays.value = list
        prefs.edit { putString(K_RELAYS, json.encodeToString(list)) }
    }

    private fun load(): List<ShareRelayEntry> {
        val raw = prefs.getString(K_RELAYS, null) ?: return emptyList()
        return runCatching { json.decodeFromString<List<ShareRelayEntry>>(raw) }.getOrDefault(emptyList())
    }
}
