package com.opentasker.core

import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import java.util.regex.Pattern
import java.util.regex.PatternSyntaxException
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Compiles every regex literal declared in production source against Android's engine.
 *
 * Android uses ICU, which rejects patterns desktop `java.util.regex` accepts. This project has
 * shipped that divergence three times: the Tasker import DOCTYPE guard, the `data.read` XML parser,
 * and a `TaskRunner` companion-object pattern whose bare `}}` made every task on every device fail
 * with `ExceptionInInitializerError`. All 1,263 JVM tests were green through that last one, because
 * a JVM suite runs against the desktop engine and structurally cannot observe the difference.
 *
 * The corpus is generated by `:app:generateRegexCorpus` into an androidTest asset.
 */
@RunWith(AndroidJUnit4::class)
class ProductionRegexIcuCompilationTest {

    @Test
    fun everyProductionRegexLiteralCompilesOnDevice() {
        val patterns = loadCorpus()

        // A missing or empty asset would otherwise let this test pass while checking nothing.
        assertTrue(
            "Regex corpus is empty; run :app:generateRegexCorpus",
            patterns.isNotEmpty(),
        )

        val rejected = patterns.mapNotNull { pattern ->
            try {
                Pattern.compile(pattern)
                null
            } catch (error: PatternSyntaxException) {
                "$pattern -> ${error.description} near index ${error.index}"
            }
        }

        assertTrue(
            "Android's ICU engine rejected ${rejected.size} production regex " +
                "literal(s):\n${rejected.joinToString("\n")}",
            rejected.isEmpty(),
        )
    }

    private fun loadCorpus(): List<String> =
        InstrumentationRegistry.getInstrumentation().context.assets
            .open(CORPUS_ASSET)
            .bufferedReader()
            .readLines()
            .filter { it.isNotBlank() }
            // The generator writes one pattern per line, so a literal newline inside a pattern is
            // escaped on the way out and restored here.
            .map { it.replace("\\n", "\n") }

    private companion object {
        const val CORPUS_ASSET = "production-regex-patterns.txt"
    }
}
