package com.opentasker.ui.charts

import kotlin.math.roundToInt

/**
 * 健康指数 — a single number, with its whole arithmetic on screen.
 *
 * ## Why this exists rather than Hume's Health Score
 *
 * Hume's is 0–900 and draws on resting heart rate, HRV, heart-rate stability, SpO₂ and sleep quality
 * — every one of which we measure. But **the weights are deliberately withheld**, and part of it comes
 * from Body Pod body-composition data that does not exist here. So their 811 cannot be reproduced, and
 * a fitted imitation would be a guess wearing the clothes of a measurement.
 *
 * Its neighbours on that screen are worse. "Metabolic Momentum", "Life Added: 1.9 days" and "Pace of
 * Aging: 0.5×" are generated by undisclosed algorithms; the vendor's own consumer report calls the
 * life-added figure a *model-based estimate, not the result of a controlled clinical study*, and notes
 * there is *no universal clinical standard for wearable biological age estimation*. A number that
 * cannot be checked and cannot be wrong is not a measurement. None of it is reproduced here.
 *
 * ## What makes this one different
 *
 * Every breakpoint below is a constant in this file, every weight is a constant in this file, and the
 * info panel prints both alongside each component's actual contribution. The index is therefore
 * falsifiable: 白い熊 can disagree with a breakpoint and change it, which is impossible with a hidden
 * formula.
 *
 * **It refuses rather than guesses.** A component whose inputs are missing is reported missing and
 * named, and the index says it is partial. It is never imputed, defaulted or quietly dropped —
 * silently scoring a night with no sleep data as though sleep were fine is precisely the failure this
 * design exists to avoid.
 *
 * The breakpoints are ordinary published physiology, not novel science: resting heart rate lower is
 * fitter, higher HRV is better autonomic function, SpO₂ below ~95 % is worth noticing, adults need
 * roughly 7–9 h of sleep with a healthy share of deep and REM. They are a reasonable reading of
 * common reference ranges, and they are visible so they can be argued with.
 *
 * Pure Kotlin, no Android: the arithmetic is the part worth testing.
 */

/** One component's contribution, including the raw measurement it came from. */
data class IndexComponent(
    val key: String,
    val label: Loc,
    /** What was measured, in its own unit. Null when the inputs were absent. */
    val measured: Double?,
    val unit: String,
    /** 0–100 for this component, or null when [measured] is null. */
    val score: Int?,
    val weight: Double,
    /** The breakpoints, best-first, for the info panel. */
    val scale: Loc,
    /** Why it is missing, when it is. */
    val missingReason: Loc? = null,
) {
    val contribution: Double get() = (score ?: 0) * weight
}

/**
 * The index. [partial] is true when any component was missing, and [missing] names them.
 *
 * [value] is renormalised over the components that were actually available, so a partial index is
 * still on a 0–100 scale — but it is labelled partial, because "84 out of four components" and "84
 * out of five" are not the same claim.
 */
data class HealthIndexResult(
    val value: Int?,
    val components: List<IndexComponent>,
    val partial: Boolean,
    val missing: List<Loc>,
) {
    /**
     * How much of the index was actually measured, 0..1.
     *
     * [value] alone cannot say whether an index is comparable with another: renormalising means a
     * score built from one component and one built from five both come back on 0–100. On a screen
     * that can print "partial" beside the number that is fine; in a **column of days** it is not,
     * because the column exists to be compared down. So the day table gates on this.
     */
    val availableWeight: Double
        get() = components.filter { it.score != null }.sumOf { it.weight }

    val band: Loc get() = HealthIndex.bandOf(value)
}

/** The measurements the index consumes. Any may be null; null means "not measured", never zero. */
data class HealthIndexInputs(
    /** 5th percentile of heart rate during the last sleep session, bpm. */
    val restingHr: Double?,
    /** Inter-quartile range of periodic heart rate during sleep, bpm. */
    val hrIqr: Double?,
    /** 5th percentile of SpO₂ over the window, %. */
    val spo2Low: Double?,
    /** Total minutes of the last sleep session. */
    val sleepMinutes: Int?,
    /** Deep + REM as a fraction of that session, 0..1. */
    val deepRemShare: Double?,
    /**
     * The day's step total.
     *
     * Null only when the band recorded no step data at all. **Zero is a real value** — a day of not
     * walking is a measurement, not an absence — so this is the one input where 0 must not be
     * confused with missing.
     */
    val steps: Double? = null,
)

object HealthIndex {

    /**
     * The index's own bands, as a step on the shared 1–5 scale.
     *
     * These are the cut points the headline has always used to print "Good" beside a 72; naming them
     * as a step is what lets a component's BAR carry the same claim as the word (白い熊, 2026-08-12:
     * the bars were tinted by value along one blue, so a shade meant something real but nothing
     * nameable, and the card looked arbitrary).
     *
     * **Applying a total's bands to one component is an extension, not a published rule** — both are
     * 0–100 on the same construction, which is what makes it defensible, and it is why each bar prints
     * its band word beside it rather than letting the colour assert it alone.
     */
    fun step(score: Int): Int = when {
        score >= 85 -> 1
        score >= 70 -> 2
        score >= 55 -> 3
        score >= 40 -> 4
        else -> 5
    }

    /** The word for a 0–100, or an em dash when there is nothing to band. */
    fun bandOf(score: Int?): Loc = when (score?.let(::step)) {
        null -> Loc("—", "—")
        1 -> Loc("Excellent", "とても良い")
        2 -> Loc("Good", "良い")
        3 -> Loc("Standard", "標準")
        4 -> Loc("Low", "低い")
        else -> Loc("Very low", "とても低い")
    }

    /**
     * Breakpoints, and where they come from.
     *
     * **These are the same numbers as the metric cards' band ladders**, and `HealthIndexTest` asserts
     * it. That is what stops the two disagreeing: a card cannot read "Standard" while the index
     * scores the same metric 15 out of 100, because both are reading one set of edges.
     *
     * ## There is no HRV component, and there was one
     *
     * It was removed on 2026-08-06 after the field it read turned out not to be HRV. Forensic
     * analysis of 2 131 records established that the `hrv` byte has **positive** correlation with
     * heart rate (+0.383 pooled, +0.179 asleep) where every real variability metric is negative; that
     * it carries **no sleep-stage information at all** (deep 21.0, light 21.0, REM 20.5 — effect size
     * ≈ 0); that it is near-i.i.d. within a state where the same record's heart rate holds an
     * autocorrelation of +0.59; and that **74 % of its variance is fixed by two binary firmware
     * flags** — sleep mode, and whether the PPG read succeeded. It is a device state index wearing
     * an HRV label.
     *
     * Its 25 % was redistributed across the four surviving components in proportion. Nothing was
     * substituted for it: there is no other field in this protocol that measures autonomic tone, and
     * inventing a stand-in would be exactly the failure this index exists to avoid.
     */
    const val HR_WORST = 85.0
    const val HR_BEST = 50.0
    const val SPO2_WORST = 90.0
    const val SPO2_BEST = 97.0
    const val IQR_WORST = 25.0
    const val IQR_BEST = 4.0

    /**
     * Steps. Added 2026-08-07 at 白い熊's instruction, at 20 %.
     *
     * The dose–response evidence for daily step count is among the better literatures in wearable
     * health — all-cause mortality falls steeply from roughly 2 500 to 7 000 steps a day and flattens
     * after — so the ramp is a real one and the clamp above [STEPS_BEST] is deliberate: walking more
     * than the plateau does not keep buying score.
     *
     * The edges are **the steps card's own band ladder** (3 000 Low→Standard, 7 500 Standard→High),
     * not the 2 500 / 8 000 the literature suggests on its own. That invariant — index breakpoints
     * ARE card breakpoints — is what stops a card reading "Standard" beside a component scoring 15,
     * and it is worth more than 500 steps of precision. The two happen to agree closely anyway.
     *
     * **It is a different KIND of input from the other four.** They are physiological state over a
     * window, mostly not under daily control; this is a behaviour total that is entirely under it. A
     * day of walking can therefore lift the index while the body's own numbers are unchanged, which
     * is what 白い熊 asked for and is worth knowing when reading a rise.
     */
    const val STEPS_WORST = 3_000.0
    const val STEPS_BEST = 7_500.0

    // --- weights, summing to 1.0 -------------------------------------------------------------
    // Steps took 20 % on 2026-08-07, out of the other four in proportion (each × 0.8: 26.4, 11.2,
    // 16.0, 26.4). Rounded to whole percent so the printed weights sum to exactly 100 rather than
    // 99 — the single point went to blood oxygen, the component furthest from a round number.
    const val W_RESTING_HR = 0.26
    const val W_STABILITY = 0.11
    const val W_SPO2 = 0.17
    const val W_SLEEP = 0.26
    const val W_STEPS = 0.20

    /**
     * A piecewise-linear map from a measurement to 0–100.
     *
     * [best] scores 100, [worst] scores 0, and everything between interpolates. Values beyond either
     * end clamp — a resting heart rate of 38 is not 130 points of health.
     */
    fun ramp(value: Double, best: Double, worst: Double): Int {
        if (best == worst) return 50
        val t = (value - worst) / (best - worst)
        return (t.coerceIn(0.0, 1.0) * 100).roundToInt()
    }

    /** Score a band: 100 inside [goodFrom]..[goodTo], falling to 0 at [zeroFrom]..[zeroTo]. */
    fun plateau(value: Double, zeroFrom: Double, goodFrom: Double, goodTo: Double, zeroTo: Double): Int =
        when {
            value < goodFrom -> ramp(value, best = goodFrom, worst = zeroFrom)
            value > goodTo -> ramp(value, best = goodTo, worst = zeroTo)
            else -> 100
        }

    fun compute(inputs: HealthIndexInputs): HealthIndexResult {
        val components = listOf(
            component(
                "resting_hr", Loc("Resting heart rate", "安静時心拍"), inputs.restingHr, "bpm",
                W_RESTING_HR,
                Loc("50 bpm or below = 100 · 85 bpm = 0", "50 bpm 以下 = 100 ／ 85 bpm = 0"),
                Loc("no heart rate during sleep", "睡眠中の心拍がありません"),
            ) { ramp(it, best = HR_BEST, worst = HR_WORST) },
            component(
                "stability", Loc("Heart-rate stability", "心拍安定性"), inputs.hrIqr, "bpm",
                W_STABILITY,
                Loc(
                    "inter-quartile range 4 bpm or below = 100 · 25 bpm = 0",
                    "四分位範囲 4 bpm 以下 = 100 ／ 25 bpm = 0",
                ),
                Loc("not enough heart rate during sleep", "睡眠中の心拍が足りません"),
            ) { ramp(it, best = IQR_BEST, worst = IQR_WORST) },
            component(
                "spo2", Loc("Blood oxygen", "血中酸素"), inputs.spo2Low, "%", W_SPO2,
                Loc("97 % or above = 100 · 90 % = 0", "97 % 以上 = 100 ／ 90 % = 0"),
                Loc("no blood-oxygen readings", "血中酸素の測定がありません"),
            ) { ramp(it, best = SPO2_BEST, worst = SPO2_WORST) },
            sleepComponent(inputs),
            component(
                "steps", Loc("Steps", "歩数"), inputs.steps, "歩", W_STEPS,
                Loc(
                    "7 500 steps or above = 100 · 3 000 = 0 (no bonus above 7 500)",
                    "7,500 歩以上 = 100 ／ 3,000 歩 = 0（7,500 歩を超えても加点なし）",
                ),
                Loc("no step records", "歩数の記録がありません"),
            ) { ramp(it, best = STEPS_BEST, worst = STEPS_WORST) },
        )

        val available = components.filter { it.score != null }
        val missing = components.filter { it.score == null }
        if (available.isEmpty()) {
            return HealthIndexResult(null, components, partial = true, missing = missing.map { it.label })
        }
        // Renormalised over what was actually measured, so a partial index still reads 0-100 — and it
        // is labelled partial so the two are never confused.
        val totalWeight = available.sumOf { it.weight }
        val value = (available.sumOf { it.contribution } / totalWeight).roundToInt().coerceIn(0, 100)
        return HealthIndexResult(
            value = value,
            components = components,
            partial = missing.isNotEmpty(),
            missing = missing.map { it.label },
        )
    }

    /**
     * Sleep scores duration and architecture together, because either alone misleads: ten hours of
     * pure light sleep is not a good night, and neither is five hours with excellent deep share.
     */
    private fun sleepComponent(inputs: HealthIndexInputs): IndexComponent {
        val minutes = inputs.sleepMinutes
        val share = inputs.deepRemShare
        if (minutes == null) {
            return IndexComponent(
                "sleep", Loc("Sleep", "睡眠"), null, "min", null, W_SLEEP,
                SLEEP_SCALE, Loc("no recent sleep record", "直近の睡眠記録がありません"),
            )
        }
        // 7-9 h is the plateau; 4 h and 12 h score zero.
        val duration = plateau(minutes.toDouble(), zeroFrom = 240.0, goodFrom = 420.0, goodTo = 540.0, zeroTo = 720.0)
        // Architecture is only blended in when it was actually measured.
        val score = if (share == null) duration else {
            (duration * 0.7 + ramp(share, best = 0.45, worst = 0.10) * 0.3).roundToInt()
        }
        return IndexComponent(
            "sleep", Loc("Sleep", "睡眠"), minutes.toDouble(), "min", score, W_SLEEP,
            SLEEP_SCALE,
        )
    }

    private fun component(
        key: String,
        label: Loc,
        measured: Double?,
        unit: String,
        weight: Double,
        scale: Loc,
        missingReason: Loc,
        score: (Double) -> Int,
    ): IndexComponent = IndexComponent(
        key = key,
        label = label,
        measured = measured,
        unit = unit,
        score = measured?.let(score),
        weight = weight,
        scale = scale,
        missingReason = if (measured == null) missingReason else null,
    )

    private val SLEEP_SCALE = Loc(
        "7–9 h = 100 · 4 h and 12 h = 0, blended 70/30 with deep+REM share (45 % or above = 100)",
        "7〜9 時間 = 100 ／ 4 時間・12 時間 = 0。深い睡眠と REM の割合 45 % 以上 = 100 を 3 割の重みで混ぜる",
    )
}
